# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "Teste"
application_url = "https://accessed-saints-chosen-donations.trycloudflare.com"
embedded = true
name = "[DEV-<Yourname>] Boilerplate app"
handle = "dev-<yourname>-boilerplate-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "<your-dev-store-url>"
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled","shop/update"]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://accessed-saints-chosen-donations.trycloudflare.com/auth/callback",
  "https://accessed-saints-chosen-donations.trycloudflare.com/auth/shopify/callback",
  "https://accessed-saints-chosen-donations.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://accessed-saints-chosen-donations.trycloudflare.com"
subpath = "boilerplate-app"
prefix = "apps"

[pos]
embedded = false
