# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
client_id = "bc974a37dcc7a95460f30979128d1bf1"
name = "[Production] Boilerplate app"
handle = "production-boilerplate-app"
application_url = "https://boxed-uri-photographer-rules.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0543ee3a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://boxed-uri-photographer-rules.trycloudflare.com/auth/callback",
  "https://boxed-uri-photographer-rules.trycloudflare.com/auth/shopify/callback",
  "https://boxed-uri-photographer-rules.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [ "app/uninstalled", "products/update", "shop/update" ]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false

[app_proxy]
url = "https://boxed-uri-photographer-rules.trycloudflare.com"
prefix = "apps"
subpath = "bundles-x"