# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a653bcfd21b56a313a4a027378c3e8d8"
application_url = "https://purchases-cook-lb-mouth.trycloudflare.com"
embedded = true
name = "[DEV-Leandro] Boilerplate app"
handle = "dev-leandro-boilerplate-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "loja-leandristica.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "shop/update" ]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://purchases-cook-lb-mouth.trycloudflare.com/auth/callback",
  "https://purchases-cook-lb-mouth.trycloudflare.com/auth/shopify/callback",
  "https://purchases-cook-lb-mouth.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://purchases-cook-lb-mouth.trycloudflare.com"
subpath = "boilerplate-app"
prefix = "apps"

[pos]
embedded = false
