# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "x"
application_url = "https://boilerplate-app-stg.zynclabs.com"
embedded = true
name = "[STG] Boilerplate app"
handle = "stg-boilerplate-app"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "https://shopify-webhook-processor-stg.zynclabs.com/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  topics = ["app/uninstalled","shop/update"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://boilerplate-app-stg.zynclabs.com/auth/callback",
  "https://boilerplate-app-stg.zynclabs.com/auth/shopify/callback",
  "https://boilerplate-app-stg.zynclabs.com/api/auth/callback"
]

[app_proxy]
url = "https://boilerplate-app-stg.zynclabs.com"
subpath = "boilerplate-app"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "leadhive-stg.myshopify.com"
automatically_update_urls_on_dev = false

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true